Lesson 5 acceptance testing
secretpray/ThinkNetica-QNA pull request #3
Opened 2021-01-05 09:59 UTC by secretpray

1. Реализовать следующие истории, начиная с acceptance-тестов (если они уже реализованы, покрыть acceptance-тестами):
  - Пользователь может создавать вопрос
  - Пользователь может просматривать список вопросов
  - Пользователь, находясь на странице вопроса, может написать ответ на вопрос (т.е. форма нового ответа должна быть прямо на странице вопроса, без перехода на другую страницу)
  - Пользователь может просматривать вопрос и ответы к нему.

 2. Добавить аутентификацию к проекту, покрыть acceptance-тестами следующие сценарии:
  - Пользователь может войти в систему
  - Пользователь может выйти из системы
  - Пользователь может зарегистрироваться в системе

 3. Реализовать следующие истоиии:
  - Только аутентифицированный пользователь может создавать вопросы и ответы
  - Автор может удалить свой вопрос или ответ, но не может удалить чужой вопрос/ответ

2021-01-11 18:10 UTC, IvanShamatov requested changes
В спеки даже не смотрел, слишком много замечаний уже и так

2021-01-11 18:10 UTC, IvanShamatov commented on app/views/questions/_form.html.slim
> +    p= f.submit 'Create', class: "add-answer", id: "add-answer"
а почему в форме для создания вопросов класс про добавление ответа?

2021-01-11 18:10 UTC, IvanShamatov commented on app/views/questions/_form.html.slim
> +  = render 'shared/errors', resource: @answer
почему в форме вопроса ошибки ответа?

2021-01-11 18:10 UTC, IvanShamatov commented on app/views/questions/_form_inline.html.slim
> +  binding.pry
что-то лишнее

2021-01-11 18:10 UTC, IvanShamatov commented on app/views/questions/show.html.slim
> +        strong= answer.user.email
слышал про N+1? вот он тут

2021-01-11 18:10 UTC, IvanShamatov commented on app/views/questions/show.html.slim
> +      - if user_signed_in? && current_user.id == answer.user_id
можно использовать safe оператор, и одним условием проверить и наличие пользователя и его авторство?
if current_user&.author?(answer)

2021-01-11 18:10 UTC, IvanShamatov commented on db/seeds.rb
> +  random_user_id = User.offset(rand(User.count)).first.id
это неправильный способ доставать рандомную запись. Тебе никто не гарантирует последовательность от 1 до общего количества. Записи удаляются, сиквенсы могут стартовать от любого числа, поэтому rand от общего числа тебе ничего не даст, с таким же успехом ты мог бы взять rand(User.count).
Правильный запрос в SQL должен быть такой 
`select id from users order by random() limit 1`
а теперь сделай это с помощью рельсы

2021-01-11 20:35 UTC, secretpray commented on app/controllers/answers_controller.rb
> +  respond_to :html, :json
Убрал. Пытался оставить задел под AJAX, но там, как оказалось, нужен js, а не json)

2021-01-11 20:36 UTC, secretpray commented on app/controllers/answers_controller.rb
> +  before_action :set_answer, only: %i(show edit update destroy)
Не думал что это так важно?! Для удобства различаемости) Исправил.

2021-01-11 20:38 UTC, secretpray commented on app/controllers/answers_controller.rb
> +  before_action :find_question, only: %i(new create)
Ок. Подправил

2021-01-11 20:39 UTC, secretpray commented on app/controllers/answers_controller.rb
> +  before_action :authenticate_user!, except: (:show)
Убрал

2021-01-11 20:40 UTC, secretpray commented on app/controllers/answers_controller.rb
> +    @answer = Answer.find(params[:id])
Не знал. Приму к сведению.

2021-01-11 20:41 UTC, secretpray commented on app/controllers/answers_controller.rb
> +    @answer = Answer.find(params[:id])
Учел в коде

2021-01-11 21:14 UTC, secretpray commented on app/models/question.rb
> +  scope :by_title, -> { reorder(title: :asc) }
Хм)

2021-01-11 21:44 UTC, secretpray commented on app/models/answer.rb
> +  scope :by_user, -> { order(user_id: :asc) }
Убрал

2021-01-11 21:44 UTC, secretpray commented on app/models/answer.rb
> +  scope :by_add, -> { order(created_at: :desc) }
Убрал

2021-01-11 21:45 UTC, secretpray commented on app/views/answers/new.html.slim — копия
> += simple_form_for([@question, @answer], local: true) do |f|
Не почистил. Убрал

2021-01-11 21:50 UTC, secretpray commented on app/views/questions/_form.html.slim
> +    p= f.submit 'Create', class: "add-answer", id: "add-answer"
Это классы для стилей css. Согласен, здесь они смотрятся несколько неуместно, но нет желания в css плодить новые сущности) Пока ни на что другое они не влияют. Если встанет вопрос их использования, например в JS, тогда по ситуации...

2021-01-11 21:50 UTC, secretpray commented on app/views/questions/_form.html.slim
> +  = render 'shared/errors', resource: @answer
Правильный вопрос) Убрал

2021-01-11 21:50 UTC, secretpray commented on app/views/questions/_form_inline.html.slim
> +  binding.pry
Точно.

2021-01-11 21:52 UTC, secretpray commented on app/views/questions/show.html.slim
> +        strong= answer.user.email
Слышал, учту. В связи с небольшим объёмом ответов на вопрос, не вижу смысла переделывать под Eager Loading

2021-01-11 21:52 UTC, secretpray commented on app/views/questions/show.html.slim
> +      - if user_signed_in? && current_user.id == answer.user_id
Так и сделал.

2021-01-11 21:53 UTC, secretpray commented on db/seeds.rb
> +  random_user_id = User.offset(rand(User.count)).first.id
Сделал вот так:
random_user_id = User.find(User.pluck(:id).sample).id

2021-01-11 21:54 UTC, secretpray commented on app/controllers/answers_controller.rb
> +    if @answer.update(answer_params)
Исправлю.

2021-01-13 07:00 UTC, IvanShamatov approved these changes
Внеси правки по спекам

2021-01-13 07:00 UTC, IvanShamatov commented on spec/support/feature_helpers.rb
> +    expect(page).to have_content question.title
это не хелпер, это очень специфичный код, который нужен только в фиче спеках вопроса, потому что завязан исключительно на вопросы. Этот title_check нигде больше не будет работать и в общий хелпер значит выносить не надо

2021-01-16 11:05 UTC, merged